ConsentViewController/Classes/ConsentViewController.swift, ConsentViewController/Classes/ConsentViewControllerError.swift, Example/ConsentViewController/ViewController.swift
TL;DR; We now: 
* load the webview in a separate function and call `onMessageReady` when the message is ready to be shown. 
* no longer add/remove the view from the superview. it's up to the parent to decide if/when the view should be added (we recommend using `onMessageReady` to add it and `onInteractionComplete` to remove it)
=> Load WebView separately

CHANGELOG.md, ConsentViewController.podspec, ConsentViewController/Classes/ConsentViewController.swift, ConsentViewController/Classes/SourcePointClient.swift, Example/ConsentViewController/ViewController.swift
Moved the API calls on secondary thread to keep main thread independent and free for UI operation.
below API's I have moved to secondary thread.
1. getSiteId
2. getGdprStatus
3. getCustomConsents
=> Moved  the API calls on secondary thread to keep main thread independent

ConsentViewController/Classes/SourcePointClient.swift
Swift 5 flattens nested optionals resulting from try? 
https://github.com/apple/swift-evolution/blob/master/proposals/0230-flatten-optional-try.md
Therefore the framework can't be built currently with Swift 5.
Using the brackets Swift 4.2 code also flattens the optional.
=> Fixes Swift 5 Syntax Error

ConsentViewController/Classes/ConsentViewController.swift, Example/ConsentViewController.xcodeproj/project.pbxproj, Example/ConsentViewController/Info.plist
On iPads, when rotating the device, the WebView would get cropped. Making it impossible for the user to scroll.
With this PR, the `ConsentViewCotntroller.webView` will be able to take the whole screen when rotating the device.
=> Fix scrolling on device rotate

ConsentViewController/Classes/ConsentViewController.swift
We always store the siteId and GDPRStatus in the `UserDefaults` but we don't we rely on them to decide if we should make a http call to get the data or not. 
From now on we always make the http call.
=> remove UserDefaults cache

ConsentViewController/Classes/ConsentViewController.swift
* call `clearAllConsentData` from within `ConsentViewController.onErrorOccurred`
* add flag `shouldCleanConsentOnError` to allow for the user to opt-in/out from cleaning the consent data on error.
=> implement shouldCleanConsentOnError flag

ConsentViewController/Classes/GDPRPropertyName.swift, Example/Pods/Pods.xcodeproj/project.pbxproj
Allows for property names with dashes (`-`).
=> change GDPRPropertyName regex validation to accept dashes

ConsentViewController/Classes/MessageWebViewController.swift
When the user double taps on the message, the webview's default behaviour is to zoom in. 
We don't like kind of behaviour though...
=> disable zoom on MessageWebView

ConsentViewController/Classes/GDPRConsentViewController.swift, ConsentViewController/Classes/OSLogger.swift, ConsentViewController/Classes/SourcePointClient.swift, Example/Pods/Pods.xcodeproj/project.pbxproj
By logging the network calls we make our lives a bit easier when debugging. 
This PR:
* makes use of the `Logger` (which in its turn make use of `os_log` function from Apple)
* add and implement the `SPLogger` (we're likely to use it later when implementing the SDK analytics)
* use the `OSLogger` on the `SimpleClient` to log all requests.
=> [SP-3497] add network logger

.github/workflows/swift.yml, ConsentViewController/Classes/GDPRAction.swift, ConsentViewController/Classes/GDPRConsentViewController.swift, Example/ConsentViewController.xcodeproj/project.pbxproj, Example/ConsentViewController/Base.lproj/Main.storyboard, Example/ConsentViewController/ViewController.swift, Example/ConsentViewController_ExampleTests/GDPRActionSpec.swift, Example/ConsentViewController_ExampleTests/MessageWebViewControllerSpec.swift
There are 3 main parts to this PR:
1. add a clear consent button to the example app
2. add a `description` attribute to `GDPRActionType` for better printing
3. add specs for `GDPRActionType` and `GDPRAction`
=> Refactor example app to have a clear button

ConsentViewController/Classes/GDPRConsentViewController.swift, ConsentViewController/Classes/SourcePointClient.swift, ConsentViewController/Classes/SourcePointRequestsResponses.swift, Example/ConsentViewController/Base.lproj/Main.storyboard, Example/ConsentViewController/ViewController.swift, Example/ConsentViewController_ExampleTests/SourcePointClientSpec.swift
It's now possible to add vendors, categories and legitimateInterestCategories consents to a given consentUUID. In other words, programatically consent an user to a list of vendors/cat/legIntCat.
* Updated SourcePointClient to use the new `custom-consent` endpoint
* Updated GDPRConsentViewController to expose `customConsentTo` method
* Updated the Example app to show off the new feature
=> SP-3524 implement customConsent API

ConsentViewController/Classes/GDPRConsentViewController.swift, ConsentViewController/Classes/GDPRConsentViewControllerError.swift, ConsentViewController/Classes/GDPRUserConsent.swift, Example/ConsentViewController_ExampleTests/GDPRConsentViewControllerSpec.swift
When calling `clearAllData` we should not only clear the data from the `UserDefaults` but the in memory attributes as well.
=> Reset in memory attributes on clearAllData

ConsentViewController/Classes/GDPRConsentViewController.swift, ConsentViewController/Classes/GDPRConsentViewControllerError.swift
There might be a case in which the `consentUUID` (gdprUUID) is empty when calling one of the post consent endpoints. In this case, rather than waiting for the endpoint to return an error we call the `onError` ourselves with an description of what's going on.
=> Check for consentUUID before posting consent

ConsentViewController/Classes/GDPRConsentViewController.swift
* stop generating a consent UUID by ourselves
* fix `didAuthIdChange` for the case when the user is logged out and transitions to logged in
=> SP-3432 fix login logout issue

ConsentViewController/Classes/GDPRConsentViewController.swift, ConsentViewController/Classes/GDPRUserConsent.swift, ConsentViewController/Classes/SourcePointClient/SimpleClient.swift, ConsentViewController/Classes/SourcePointClient/SourcePointClient.swift, Example/ConsentViewController.xcodeproj/project.pbxproj, Example/ConsentViewController.xcodeproj/xcshareddata/xcschemes/ConsentViewController_ExampleTests.xcscheme, Example/ConsentViewController/ViewController.swift, Example/ConsentViewController_ExampleTests/GDPRConsentViewControllerSpec.swift, Example/ConsentViewController_ExampleTests/GDPRUserConsentsSpec.swift, Example/ConsentViewController_ExampleTests/SimpleClientSpec.swift
This PR expands the `GDPRUserConsent` with the `VendorGrants` field. 
The `VendorGrants` field is a dictionary in the shape of:
```js
{
vendorId: {
vendorGrant: Bool,
purposeGrants: {
purposeId: Bool,
// more purposes here
}
}
// more vendors here
}
```
All vendors in the vendor list will be present in the `vendorGrants` object. The `vendorGrant` property on each vendor will indicate if that vendor has all the purposes granted (consented in the legal basis), thus, the vendor is consented too.
=> SP-3526 add GPDRVendorGrants to GDPRUserConsent

ConsentViewController/Assets/GDPRJSReceiver.js, ConsentViewController/Classes/GDPRConsentViewControllerError.swift, ConsentViewController/Classes/MessageWebViewController.swift, Example/ConsentViewController_ExampleTests/GDPRConsentViewControllerErrorSpec.swift
We're still not getting [specific error messages](https://sourcepoint.atlassian.net/browse/SP-3809?focusedCommentId=44334) but that's beyond our scope.
With this PR we make use of @MarkGeeRomano recent work, related to dispatching an error event when something goes bad.
=> SP-3679 capture error events on JSReceiver

ConsentViewController/Classes/GDPRAction.swift, ConsentViewController/Classes/GDPRCampaignEnv.swift, ConsentViewController/Classes/GDPRConsentViewController.swift, ConsentViewController/Classes/GDPRMessageViewController.swift, ConsentViewController/Classes/GDPRNativeMessageViewController.swift, ConsentViewController/Classes/MessageWebViewController.swift, ConsentViewController/Classes/SourcePointClient/SourcePointClient.swift, Example/ConsentViewController.xcodeproj/project.pbxproj, Example/ConsentViewController.xcodeproj/xcshareddata/xcschemes/ConsentViewController_Example.xcscheme, Example/ConsentViewController_ExampleTests/GDPRActionSpec.swift, Example/ConsentViewController_ExampleTests/GDPRConsentViewControllerSpec.swift, Example/ConsentViewController_ExampleTests/GDPRNativeMessageViewControllerSpec.swift, Example/ConsentViewController_ExampleTests/Helpers/ConnectivityMock.swift, Example/ConsentViewController_ExampleTests/Helpers/GDPRLocalStorageMock.swift, Example/ConsentViewController_ExampleTests/Helpers/GDPRUIiDelegateMock.swift, Example/ConsentViewController_ExampleTests/Helpers/HttpMock.swift, Example/ConsentViewController_ExampleTests/Helpers/InMemoryStorageMock.swift, Example/ConsentViewController_ExampleTests/Helpers/MockConsentDelegate.swift, Example/ConsentViewController_ExampleTests/Helpers/SourcePointClientMock.swift, Example/ConsentViewController_ExampleTests/LocalStorage/GDPRUserDefaultsSpec.swift, Example/ConsentViewController_ExampleTests/MessageWebViewControllerSpec.swift, Example/ConsentViewController_ExampleTests/SourcePointClient/SimpleClientSpec.swift, Example/ConsentViewController_ExampleTests/SourcePointClient/SourcePointClientSpec.swift
Ensure `onConsentReady` is always called after every action with exception of:
1. `ShowPrivacyOptions`
2. `PMCancel` when in the 2nd layer message.
=> SP-3631 always call on consent ready

ConsentViewController/Classes/GDPRConsentViewController.swift, ConsentViewController/Classes/SourcePointClient/ActionRequestResponse.swift, ConsentViewController/Classes/SourcePointClient/CustomConsentRequestResponse.swift, ConsentViewController/Classes/SourcePointClient/MessageRequestResponse.swift, ConsentViewController/Classes/SourcePointClient/SourcePointClient.swift, ConsentViewController/Classes/SourcePointRequestsResponses.swift, Example/ConsentViewController.xcodeproj/project.pbxproj, Example/ConsentViewController_ExampleTests/GDPRCampaignEnvSpec.swift, Example/ConsentViewController_ExampleTests/MessageRequestSpec.swift, Example/Pods/Pods.xcodeproj/project.pbxproj
The wrong encoding of the `GDPRCampaignEnv` on iOS 10 and bellow is causing the SourcePoint client to create the wrong body for the wrapper API when getting the message url. This PR fixes this issue by "manually" encoding/decoding the `MessageRequest` based on the iOS version.
=> SP-4138 fix campaignEnv encoding ios10

ConsentViewController/Classes/GDPRMessage.swift, Example/ConsentViewController_ExampleTests/GDPRMessageSpec.swift
This PR fixes an issue when `GDPRMessage` -> `JSON` encoding produced a JSON without `choiceType` and `choiceId` fields for the `MessageAttributeAction` objects. 
- `GDPRMessage` JSON Encoding
=> Fix issue when GDPRMessage didn't have all its fields present when JSON encoded

Example/SPGDPRExampleAppUITests/SPGDPRExampleAppUITests.swift
The ui tests for the Example app is failing (sometimes) https://github.com/SourcePointUSA/ios-cmp-app/actions/runs/197651154/workflow
I suspect it's due to the asynchronous nature of the `customConsentTo` feature.
=> refactor example app ui tests

ConsentViewController/Classes/MessageWebViewController.swift, Example/ConsentViewController_ExampleTests/MessageWebViewControllerSpec.swift
This PR fixes the following issue https://github.com/SourcePointUSA/ios-cmp-app/issues/229
=> #229 Make sure that SDK calls onError delegate when webView fails to load url

ConsentViewController/Classes/GDPRAction.swift, ConsentViewController/Classes/SPGDPRArbitraryJson.swift, ConsentViewController/Classes/SourcePointClient/ActionRequestResponse.swift, ConsentViewController/Classes/SourcePointClient/SourcePointClient.swift, Example/ConsentViewController.xcodeproj/project.pbxproj, Example/ConsentViewController_ExampleTests/ActionRequestSpec.swift, Example/ConsentViewController_ExampleTests/GDPRActionSpec.swift, Example/ConsentViewController_ExampleTests/SourcePointClient/SourcePointClientSpec.swift
The publisher can now add their own arbitrary data to the action payload. 
```swift
// GDPRConsentDelegate
func onAction(_ action: GDPRAction) {
action.publisherData = ["my data": try? SPGDPRArbitraryJson("foo bar")]
}
```
This will be encoded into:
```json
{
...,
"pubData": {
"my data": "foo bar"
}
}
```
and sent to our endpoints / logs. Where it can then be retrieved via APIs.
=> [SP-4113] implement publisherData on GDPRAction class

.github/workflows/swift.yml, ConsentViewController/Assets/GDPRJSReceiver.js, ConsentViewController/Classes/GDPRAction.swift, ConsentViewController/Classes/GDPRNativeMessageViewController.swift, ConsentViewController/Classes/MessageWebViewController.swift, ConsentViewController/Classes/SourcePointClient/ActionRequestResponse.swift, ConsentViewController/Classes/SourcePointClient/SourcePointClient.swift, Example/ConsentViewController_ExampleTests/ActionRequestSpec.swift, Example/ConsentViewController_ExampleTests/GDPRActionSpec.swift, Example/ConsentViewController_ExampleTests/MessageWebViewControllerSpec.swift, Example/ConsentViewController_ExampleTests/SourcePointClient/SourcePointClientSpec.swift, Example/Pods/Pods.xcodeproj/project.pbxproj, Example/SourcePointMetaAppUITests/Helpers/MetaApp.swift
1. In Web message case we are sending **consentLanguage** to sendConsent API call, consentLanguage is captured from action event.
1. In Native message case we are sending **Locale** value as consentLanguage value to sendConsent API call.
=> [SP-5244] Add support for consent language

.github/workflows/swift.yml, ConsentViewController/Classes/GDPRConsentViewController.swift, ConsentViewController/Classes/MessageWebViewController.swift, Example/ConsentViewController_ExampleTests/GDPRConsentViewControllerSpec.swift
After calling the `.customConsentTo()` method, the `GDPRConsentViewController#userConsents` is not updated. 
This PR fixes this issue (and updates the GitHub workflow file to execute test targets in parallel).
=> SP-5535 update userConsents after calling customConsentTo

.github/workflows/testingMatrix.yml
Added workflow to run Example App, Native App and MetaApp to run on iOS 12.4, 13.7 and 14.3
=> [SP-5691] Add setup for Github action testing matrix

ConsentViewController/Classes/GDPRConsentViewControllerError.swift, ConsentViewController/Classes/MessageWebViewController.swift, ConsentViewController/Classes/SourcePointClient/SimpleClient.swift, ConsentViewController/Classes/SourcePointClient/SourcePointClient.swift, Example/ConsentViewController_ExampleTests/GDPRConsentViewControllerErrorSpec.swift, Example/ConsentViewController_ExampleTests/GDPRConsentViewControllerSpec.swift, Example/ConsentViewController_ExampleTests/Helpers/HttpMock.swift, Example/ConsentViewController_ExampleTests/Helpers/SourcePointClientMock.swift, Example/ConsentViewController_ExampleTests/MessageWebViewControllerSpec.swift, Example/ConsentViewController_ExampleTests/SourcePointClient/SimpleClientSpec.swift, Example/ConsentViewController_ExampleTests/SourcePointClient/SourcePointClientSpec.swift, Example/SPGDPRExampleAppUITests/SPGDPRExampleAppUITests.swift
1. Refactor error classes and their usage to align with the new [error list ](https://docs.google.com/spreadsheets/d/1MnzMbXZIPv4kT5GXoRUG9b3ks4_NGR8cdlbAy19J4BY/edit?ts=5fce0e32#gid=995431333) (this list will be soon public and hosted in a git repo).
2. Refactor the way we deal with query params in our `MessageWebViewController`. No longer storing the query params as a property.
=> SP-3552 add error codes

ConsentViewController/Classes/SPConsentManager.swift, ConsentViewController/Classes/SPMessageLanguage.swift, ConsentViewController/Classes/SourcePointClient/MessageRequest.swift, ConsentViewController/Classes/SourcePointClient/SourcePointClient.swift
The messageLanguage property on SPConsentManager is now passed into the getMessages method and allows retrieval of localized consent messages on iOS.
=> Use messageLanguage property in getMessages request

ConsentViewController/Classes/LocalStorage/SPLocalStorage.swift, ConsentViewController/Classes/LocalStorage/SPUserDefaults.swift, ConsentViewController/Classes/SPConsentManager.swift
Property id is necessary when loading a PM that belongs to a property group. 
We currently receive `propertyId` from the call to `/get_messages` and keep it in memory. But if the SDK is instantiated only for loading the PMs, the field would be `nil`. 
This PR fixes this issue by storing the `propertyId` in the local storage (UserDefaults) and using it whenever necessary.
=> add propertyId to local storage

ConsentViewController/Classes/SPConsentManager.swift, ConsentViewController/Classes/SPDelegate.swift, Example/ConsentViewController/ViewController.swift
* implement `onSPFinished` delegate method
* make sure `onAction` is always called on the main thread
---
The `onSPFinished` delegate method is guaranteed to be called once at the end of the SDK's lifecycle unless something goes wrong (in this case, the `onError` will be called instead).
=> SP-8097 implement `onSPFinished`

ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/CCPA/SPCCPAManagePreferenceViewController.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/CCPA/SPCCPANativePrivacyManagerViewController.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/CCPA/SPCCPANativePrivacyManagerViewController.xib, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/CCPA/SPCCPAPartnersViewController.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/GDPR/SPGDPRManagePreferenceViewController.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/GDPR/SPGDPRNativePrivacyManagerViewController.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/GDPR/SPGDPRNativePrivacyManagerViewController.xib, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/GDPR/SPGDPRPartnersViewController.swift
Now user cannot be stuck in the topmost cells of categoryTableView and left navigation click always leads to "Accept All" button
=> [SP-8880] focusGuide added between acceptButton and every cell in categoryTableView + between every button in actionButtons UIStack

ConsentViewController/Classes/SPConsentManager.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/CCPA/SPCCPANativePrivacyManagerViewController.swift, README.md
Now `SPConsentManager` fires `onConsentReady` instead of `onError` IF ` SPUserData` is not empty in `SPUserDefaults`
=> [DIA-1000] gracefully degradation onError

ConsentViewController/Classes/Constants.swift, ConsentViewController/Classes/SPConsentManager.swift, ConsentViewController/Classes/SourcePointClient/ChoiceRequests.swift, ConsentViewController/Classes/SourcePointClient/ChoiceResponses.swift, ConsentViewController/Classes/SourcePointClient/SourcePointClient.swift, Example/ConsentViewController_ExampleTests/Helpers/SourcePointClientMock.swift, Example/ConsentViewController_ExampleTests/SourcePointClient/SourcePointClientSpec.swift, Example/Pods/Pods.xcodeproj/project.pbxproj
@Nevazhnovu @carmelo-iriti this PR implements the POST request to choice endpoints. The post request will be made after the GET in this order:
1. user taps on an action
2. if accept-all / reject-all -> call GET consent-all / reject-all endpoint
3. call POST /choice/gdpr|ccpa/actionTypeId(1,11, etc) <-- this is the endpoint implemented
The logic wiring all the endpoints together, storing consent, etc, will be implemented in #384 or subsequent PRs.
=> DIA-1351 implement POST consent

README.md
Google additional consent string is stored in `IABTCF_AddtlConsent` in user local storage
=> [HCD-327] Google Additional Consent

ConsentViewController/Classes/OSLogger.swift, ConsentViewController/Classes/SourcePointClient/SimpleClient.swift, ConsentViewController/Classes/Views/iOS/SPWebMessageViewController.swift, Example/ConsentViewController.xcodeproj/project.pbxproj, Example/ConsentViewController.xcworkspace/xcshareddata/swiftpm/Package.resolved, Example/ConsentViewController/Info.plist, Example/ConsentViewController/ViewController.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SourcePointClient/SPLoggerMock.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SourcePointClient/SimpleClientSpec.swift
We now can log several events to XCode console without using `print` and without polluting our client's console by using `os_log`. 
With the new log levels, `debug` is only active on our Example app.
=> Make better use of `SPLogger`

ConsentViewController/Classes/SPConsentManager.swift, ConsentViewController/Classes/SPDeviceManager.swift, ConsentViewController/Classes/SourcePointClient/PvDataRequestResponse.swift, ConsentViewController/Classes/SourcePointClient/SourcePointClient.swift, ConsentViewController/Classes/SourcePointClient/SourcepointClientCoordinator.swift, Example/ConsentViewController.xcodeproj/project.pbxproj, Example/ConsentViewController_ExampleTests/Helpers/LocalStorageMock.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SPClientCoordinatorSpec.swift, Example/ConsentViewController_ExampleTests/SPDeviceSpec.swift
This PR addresses 2 items:
The SDK now correctly implements the following logic, related to state management when `authId` changes:
1. `authId` changes from `nil` -> `"something"`: state is persisted (consent is then linked to the current uuid)
2. `authId` changes from `"something"` -> `nil`: state is persisted (stored `authId` remains `"something"`)
3. `authId` changes from `"something"` -> `"something else"`: state is reset (and `authId` becomes `"something else"`)
The `/pv-data` endpoint not only logs a "pageview" but also returns a new consent uuid for a given campaign.
Previously the SDK would not wait for the response of `/pv-data`. And this causes issues with reporting as well as a missing consent uuid in the stored consent data (until the user takes a consent action).
=> DIA-2065 / DIA-2120 fix state management for authenticated consent and handle pv-data response

.github/workflows/swift.yml, ConsentViewController/Classes/Constants.swift, ConsentViewController/Classes/SourcePointClient/ChoiceRequests.swift, ConsentViewController/Classes/SourcePointClient/ConsentRequestResponse.swift, ConsentViewController/Classes/SourcePointClient/IncludeData.swift, ConsentViewController/Classes/SourcePointClient/MessageRequest.swift, ConsentViewController/Classes/SourcePointClient/MessagesRequest.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/Common/SPPMHeader.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/GDPR/SPGDPRNativePrivacyManagerViewController.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SourcePointClient/UnmockedSourcepointClientSpec.swift, Example/NativePMExampleApp/AppDelegate.swift, Example/NativePMExampleApp/ViewController.swift, Example/NativePMExampleAppUITests/NativePMApp.swift, Example/NativePMExampleAppUITests/NativePMUITests.swift, Example/Pods/Target Support Files/ConsentViewController-tvOS/ConsentViewController-tvOS-Info.plist
=> DIA-1678 / DIA-1837 add support to tvOS and translation logic

ConsentViewController/Classes/SPConsentManager.swift, ConsentViewController/Classes/SourcePointClient/MetaDataRequestResponse.swift, ConsentViewController/Classes/SourcePointClient/SimpleClient.swift, ConsentViewController/Classes/SourcePointClient/SourcepointClientCoordinator.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SPClientCoordinatorSpec.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SourcePointClient/UnmockedSourcepointClientSpec.swift, Example/ConsentViewController_ExampleTests/SPConsentManagerSpec.swift
=> [DIA-2061] `childPmId` is saved to `UserDefaults` when it comes in `/meta-data` response

ConsentViewController/Classes/SourcePointClient/MetaDataRequestResponse.swift, ConsentViewController/Classes/SourcePointClient/SourcePointClient.swift, ConsentViewController/Classes/SourcePointClient/SourcepointClientCoordinator.swift, Example/ConsentViewController_ExampleTests/Helpers/SourcePointClientMock.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SourcePointClient/UnmockedSourcepointClientSpec.swift
This fix removes data from the metadata query param to the meta-data endpoint. The data removed is harming our ability to cache meta-data response, thus increasing our costs and response times.
=> DIA-2453 fix meta-data's metadata query param

ConsentViewController/Classes/SourcePointClient/ChoiceAllResponse.swift, ConsentViewController/Classes/SourcePointClient/SourcePointClient.swift, Example/ConsentViewController_ExampleTests/Helpers/SourcePointClientMock.swift
The requests to `GET choice/consent-all` and `GET choice/reject-all` have all the correct params. This PR only renames a class to be more specific.
=> DIA-2461 refactor ChoiceAll request params

ConsentViewController/Classes/Consents/SPCCPAConsent.swift, ConsentViewController/Classes/LocalStorage/SPLocalStorage.swift, ConsentViewController/Classes/LocalStorage/SPUserDefaults.swift, ConsentViewController/Classes/SPConsentManager.swift, ConsentViewController/Classes/SourcePointClient/ChoiceAllResponse.swift, ConsentViewController/Classes/SourcePointClient/ChoiceResponses.swift, ConsentViewController/Classes/SourcePointClient/ConsentStatusResponse.swift, ConsentViewController/Classes/SourcePointClient/IncludeData.swift, ConsentViewController/Classes/SourcePointClient/SourcepointClientCoordinator.swift, Example/ConsentViewController.xcodeproj/project.pbxproj, Example/ConsentViewController_ExampleTests/Helpers/CustomMatchers.swift, Example/ConsentViewController_ExampleTests/Helpers/LocalStorageMock.swift, Example/ConsentViewController_ExampleTests/Helpers/SourcePointClientMock.swift, Example/ConsentViewController_ExampleTests/LocalStorage/SPUserDefaultsSpec.swift, Example/ConsentViewController_ExampleTests/SPCCPAConsentSpec.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SourcePointClient/UnmockedSourcepointClientSpec.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SourcepointCoordinatorMock.swift, Example/ConsentViewController_ExampleTests/SPConsentManagerSpec.swift, Example/ConsentViewController_ExampleTests/SPDeviceSpec.swift, Example/SPGDPRExampleAppUITests/Helpers/CustomMatchers.swift
[DIA-2292](https://sourcepoint.atlassian.net/browse/DIA-2292)
[DIA-2292]: https://sourcepoint.atlassian.net/browse/DIA-2292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DIA-2292 store GPPData

ConsentViewController/Classes/Consents/SPCCPAConsent.swift, ConsentViewController/Classes/SPCampaigns.swift, ConsentViewController/Classes/SourcePointClient/ChoiceRequests.swift, ConsentViewController/Classes/SourcePointClient/IncludeData.swift, ConsentViewController/Classes/SourcePointClient/MessageRequest.swift, ConsentViewController/Classes/SourcePointClient/MessagesRequest.swift, ConsentViewController/Classes/SourcePointClient/SourcePointClient.swift, ConsentViewController/Classes/SourcePointClient/SourcepointClientCoordinator.swift, Example/ConsentViewController.xcodeproj/project.pbxproj, Example/ConsentViewController_ExampleTests/Helpers/SourcePointClientMock.swift, Example/ConsentViewController_ExampleTests/IncludeDataSpec.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SPClientCoordinatorSpec.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SourcePointClient/SourcePointClientSpec.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SourcePointClient/UnmockedSourcepointClientSpec.swift, Example/ConsentViewController_ExampleTests/SPGPPConcifgSpec.swift, Example/ConsentViewController_ExampleTests/SPGPPConfigSpec.swift, Example/ObjC-ExampleApp/ViewController.m, Example/ObjC-ExampleAppUITests/CustomMatchers.swift, Example/ObjC-ExampleAppUITests/ExampleApp.swift, Example/ObjC-ExampleAppUITests/ObjC_ExampleAppUITests.swift
In the temporary GPP solution, the client should have the option to set some flags for GPP. 
Those flags are exposed as an attribute of `SPCampaigns` called `gppConfig: SPGPPConfig`. 
Although the config is available for all campaigns, the SDK only utilises the gppConfig of the ccpa campaign.
=> DIA-2478 expose GPP config through SPCampaigns

ConsentViewController/Classes/SourcePointClient/SourcepointClientCoordinator.swift, Example/ConsentViewController_ExampleTests/Helpers/SourcePointClientMock.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SPClientCoordinatorSpec.swift
When new consent data is introduced (such as `GPPData`), the SDK will need to call `/consent-status` . 
We’ll implement that logic via local data versioning.
1. The SDK will have a hardcoded version value, starting at 1
2. The SDK will have a stored local data version.
3. When calling loadMessage , the SDK checks if its stored local data version is different than the hardcoded one.
1. If version is different, call /consent-status (or authId is present)
* on /consent-status response, update stored local data version to be equal to hardcoded one
2. If version is the same, message flow continues
Following the logic above, whenever we determine the SDK should get new consent data, we simply increase the hardcoded version and release the code.
In the future we can think of having an endpoint …
=> DIA-2541 implement local data versioning

ConsentViewController/Classes/Consents/SPGDPRConsent.swift, ConsentViewController/Classes/Extensions/Date.swift, ConsentViewController/Classes/SPDate.swift, ConsentViewController/Classes/SourcePointClient/ChoiceAllResponse.swift, ConsentViewController/Classes/SourcePointClient/ChoiceResponses.swift, ConsentViewController/Classes/SourcePointClient/MessagesResponse.swift, ConsentViewController/Classes/SourcePointClient/SourcepointClientCoordinator.swift, Example/ConsentViewController_ExampleTests/Helpers/SourcePointClientMock.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SPClientCoordinatorSpec.swift, Example/ConsentViewController_ExampleTests/SPConsentManagerSpec.swift, Example/ConsentViewController_ExampleTests/SPConsentSpec.swift, Example/ConsentViewController_ExampleTests/SPGDPRConsentsSpec.swift, Example/Pods/Pods.xcodeproj/project.pbxproj
* add `expirationDate` to response classes
* add `expirationDate` to `SPGDPRConsent` class
* on `.loadMessage`, set GDPR consent back to `.empty` if `exiprationDate < today`
CCPA will be implemented in a different PR.
=> DIA-2895 GDPR consent expiration

ConsentViewController/Classes/Consents/SPCCPAConsent.swift, ConsentViewController/Classes/Consents/SPUSNatConsent.swift, ConsentViewController/Classes/Consents/SPUserData.swift, ConsentViewController/Classes/SPCampaigns.swift, ConsentViewController/Classes/SourcePointClient/MetaDataRequestResponse.swift, ConsentViewController/Classes/SourcePointClient/SourcepointClientCoordinator.swift, Example/ConsentViewController.xcodeproj/project.pbxproj, Example/ConsentViewController_ExampleTests/Helpers/SourcePointClientMock.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SPClientCoordinatorSpec.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SourcePointClient/UnmockedSourcepointClientSpec.swift, Example/ConsentViewController_ExampleTests/SPConsentSpec.swift, Example/ConsentViewController_ExampleTests/SPUSNatConsentSpec.swift, Example/Pods/Pods.xcodeproj/project.pbxproj
* Implement new campaign type `USNatCampaign`
* Implement new consent type `SPUSNatConsent`
* Expand `SPUserData` to contain `SPUSNatConsent`
* Expand `/meta-data` request/response to contain `usnat` 
* handle `/meta-data` when calling response `.loadMessages`
* Add tests for `SPCoordinator` regarding USNat `/meta-data`
Since usnat is only available on stage and many tests rely on ids present only on prod, several tests were skipped. Only the ones related to the feature will run. We'll revert that back when usnat is in preprod and we're close to merge to develop.
=> DIA-2621 add usnat to `/meta-data`

ConsentViewController/Classes/Consents/CampaignConsent.swift, ConsentViewController/Classes/Consents/LastMessageData.swift, ConsentViewController/Classes/Consents/SPCCPAConsent.swift, ConsentViewController/Classes/Consents/SPGDPRConsent.swift, ConsentViewController/Classes/Consents/SPUSNatConsent.swift, ConsentViewController/Classes/SPCampaignType.swift, ConsentViewController/Classes/SourcePointClient/MessagesRequest.swift, ConsentViewController/Classes/SourcePointClient/MessagesResponse.swift, ConsentViewController/Classes/SourcePointClient/SourcepointClientCoordinator.swift, Example/ConsentViewController_ExampleTests/Helpers/CustomMatchers.swift, Example/ConsentViewController_ExampleTests/SPCCPAConsentSpec.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SPClientCoordinatorSpec.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SourcePointClient/SourcePointClientSpec.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SourcePointClient/UnmockedSourcepointClientSpec.swift, Example/ConsentViewController_ExampleTests/SPConsentSpec.swift, Example/ConsentViewController_ExampleTests/SPUSNatConsentSpec.swift, Example/Pods/Pods.xcodeproj/project.pbxproj
* extracted `CampaignConsent` and `LastMessageData` to their own files
* refactored the way we handle consent data coming from the `/messages` response moving the logic to convenience inits of `SPCCPAConsent`, `SPGDPRConsent` and (newly created) `SPUSNatConsent`
* added a custom matcher to test `SPDates` in a more convenient way
* updated `SPUSNatConsent` with more consent data attributes
* added `usnat` campaign type
* added `usnat` to `/messages` request and response
* update `state.usnat` on `/messages`' response
=> DIA-2622 add `usnat` to `/messages`

ConsentViewController/Classes/SPConsentManager.swift, ConsentViewController/Classes/SPMessageUIDelegate.swift, ConsentViewController/Classes/Views/iOS/SPWebMessageViewController.swift, Example/ConsentViewController_ExampleTests/GenericWebMessageViewControllerSpec.swift, Example/ConsentViewController_ExampleTests/Helpers/CustomMatchers.swift, Example/ConsentViewController_ExampleTests/MessageUIDelegateMock.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SourcePointClient/UnmockedSourcepointClientSpec.swift
Fix a regression introduced by #499 in which the gdpr consent uuid value and query param would be used also for ccpa campaigns when loading the PM from the 1st layer message.
=> Fix UUID query param for PM URL

ConsentViewController/Classes/Consents/SPCCPAConsent.swift, ConsentViewController/Classes/Consents/SPGDPRConsent.swift, ConsentViewController/Classes/Consents/SPUSNatConsent.swift, ConsentViewController/Classes/SourcePointClient/ConsentStatusMetadata.swift, ConsentViewController/Classes/SourcePointClient/ConsentStatusResponse.swift, ConsentViewController/Classes/SourcePointClient/MessagesResponse.swift, ConsentViewController/Classes/SourcePointClient/SourcepointClientCoordinator.swift, Example/ConsentViewController_ExampleTests/Helpers/SourcePointClientMock.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SPClientCoordinatorSpec.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SourcePointClient/UnmockedSourcepointClientSpec.swift
* refactored a data mapping from `Consent` to `SPCCPAConsent`, `SPGDPRConsent` and `SPUSNatConsent` classes. Those mappings were `convenience init`'s on each of those classes and they are now a method called `.toConsent` on the `Consent` class.
* added `usnat` to `/consent-status` request, response and response handler on SPCoordinator
* added tests for authenticated consent on SPCoordinator (currently failing because `/consent-status` returns an new `uuid` every time it's called with the same `authId`
=> DIA-2625 add usnat to `/consent-status`

ConsentViewController/Classes/SPCampaigns.swift, ConsentViewController/Classes/SourcePointClient/ConsentStatusMetadata.swift, ConsentViewController/Classes/SourcePointClient/SourcepointClientCoordinator.swift, Example/ConsentViewController_ExampleTests/Helpers/SourcePointClientMock.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SPClientCoordinatorSpec.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SourcePointClient/UnmockedSourcepointClientSpec.swift
* fixed an issue with `/pv-data` being called for campaigns that are not in the config ✅ 
* fixed an issue with `/consent-status` being called in fresh installs (when `localVersion` is `nil`) ✅ 
* added `transitionCCPAAuth` flag to `SPConfig` so clients can choose to transfer their CCPA authenticated consent to USNat ✅
* implemented logic to transfer CCPA opted-out consent over to USNat ✅
=> DIA-3249 handle ccpa opt-outs

ConsentViewController.podspec, ConsentViewController/Classes/LocalStorage/SPUserDefaults.swift, ConsentViewController/Classes/SPCampaigns.swift, ConsentViewController/Classes/SPGPPConfig.swift, ConsentViewController/Classes/SourcePointClient/SourcepointClientCoordinator.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SPClientCoordinatorSpec.swift, Example/Pods/Local Podspecs/ConsentViewController.podspec.json, Example/Pods/Target Support Files/ConsentViewController-iOS/ConsentViewController-iOS-Info.plist, Example/Pods/Target Support Files/ConsentViewController-tvOS/ConsentViewController-tvOS-Info.plist, README.md
=> DIA-3524 support legacy uspstring in usnat

ConsentViewController/Classes/Consents/SPCCPAConsent.swift, ConsentViewController/Classes/SPConsentManager.swift, ConsentViewController/Classes/SourcePointClient/SourcepointClientCoordinator.swift, Example/ConsentViewController_ExampleTests/Helpers/CustomMatchers.swift, Example/ConsentViewController_ExampleTests/SPCCPAConsentSpec.swift
* assign default value to `signedLspa` and `expirationDate` attribute when decoding `SPCCPAConsent` object
* make sure to update consent data when `localVersion != State.version` even when `localVersion` is `nil`
=> DIA-3617 fix gdpr consents disappearing on SDK update

ConsentViewController/Classes/Extensions/SPURLExtensions.swift, ConsentViewController/Classes/Views/iOS/SPWebViewExtensions.swift, Example/AuthExample/HomeViewController.swift, Example/AuthExample/LoginViewController.swift
In certain cases, when serialising `consents.webConsents` to string, the resulting string would be invalid when interpolating inside a javascript context.
This PR fixes this issue by introducing the struct `PreloadConsentsPayload` and using that when injecting javascript instead of string interpolating `.webConsents` directly.
=> DIA-3811 preload consents not working

ConsentViewController/Classes/Consents/SPUserData.swift, ConsentViewController/Classes/SPConsentManager.swift, ConsentViewController/Classes/SPError.swift, ConsentViewController/Classes/SourcePointClient/SimpleClient.swift, ConsentViewController/Classes/SourcePointClient/SourcepointClientCoordinator.swift
* add new Errors cases
* make sure network is interrupted on error
* refactor graceful degradation condition
=> DIA-2963 fix `onError` not called for timeouts

ConsentViewController/Classes/Consents/SPUserData.swift
Hey,
in our React Native app we would like to read out the webConsents ourselves, so we can inject them manually instead of relying on `WKWebView.loadConsent`.
For this we need to access the webConsents
Does this make sense?
Best,
Finn
=> Make webConsents public

ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/CCPA/SPCCPACategoryDetailsViewController.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/CCPA/SPCCPAManagePreferenceViewController.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/CCPA/SPCCPAPartnersViewController.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/CCPA/SPCCPAVendorDetailsViewController.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/Common/SPNativeScreenViewController.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/GDPR/SPGDPRCategoryDetailsViewController.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/GDPR/SPGDPRManagePreferenceViewController.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/GDPR/SPGDPRPartnersViewController.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/GDPR/SPGDPRVendorDetailsViewController.swift
tvOS' views that contained sectioned UITableView, rendered raw html tags on their section headers. 
This PR refactor those cases to use the `loadLabelText` function (which takes into account `htmlToAttributedString` when rendering labels).
=> use `loadLabelText` on tvOS UITableViews

ConsentViewController/Classes/SourcePointClient/SourcePointClient.swift, ConsentViewController/Classes/SourcePointClient/SourcepointClientCoordinator.swift, Example/ConsentViewController_ExampleTests/Helpers/CustomMatchers.swift, Example/ConsentViewController_ExampleTests/Helpers/SourcePointClientMock.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SourcePointClient/SourcePointClientSpec.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SourcePointClient/UnmockedSourcepointClientSpec.swift
This change will allow wrapper (our backend) to take the idfa status into consideration when returning consent data.
=> DIA-3950 add idfaStatus query param to GET choice requests

ConsentViewController/Classes/SourcePointClient/SourcepointClientCoordinator.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SPClientCoordinatorSpec.swift
The SDK won't call `/messages` if the user has accepted all. As a result, if the property changes vendor list, the user won't be remessaged. 
This PR fixes this issue by checking the vendorListId present in the response of `/meta-data` and, if different than the current one, purging that legislation's consent from local storage.
=> DIA-2956 expire consent based on vendorListId change

ConsentViewController/Classes/SourcePointClient/SourcepointClientCoordinator.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SPClientCoordinatorSpec.swift
This PR addresses an edge case in which the developer might change the property or account id provided to the SDK and the SDK would keep consent data regardless.
Since some endpoints might not be called once the user has accepted all, we need to "manually" check if property id or account id changed and reset state if so.
=> DIA-3283 expire consent if propertyId or accountId change

ConsentViewController/Assets/javascript/SPJSReceiver.js
Fix an issue causing `messageId` to be absent on the call to `POST /choice`, potentially messing up with reporting.
=> DIA-4868 add messageId to JSReceiver

ConsentViewController/Classes/SourcePointClient/SourcepointClientCoordinator.swift
[DIA-5336](https://sourcepoint.atlassian.net/browse/DIA-5336)
[iOS] SDK 7.7.7 is not handling authId Properly for G & J
[DIA-5336]: https://sourcepoint.atlassian.net/browse/DIA-5336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DIA-5336] Make `hasLocalData` always `false`

ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/GDPR/SPGDPRVendorDetailsViewController.swift
[DIA-5446](https://sourcepoint.atlassian.net/browse/DIA-5446) QR code translation missing in vendor details view
[DIA-5446]: https://sourcepoint.atlassian.net/browse/DIA-5446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DIA-5446] Add translation for `PolicyQrCodeLabel`

ConsentViewController/Classes/Constants.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/Common/SPNativeScreenViewController.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/GDPR/SPGDPRVendorDetailsViewController.swift
[DIA-5445](https://sourcepoint.atlassian.net/browse/DIA-5445) Random untranslated text element in vendor details view
[DIA-5445]: https://sourcepoint.atlassian.net/browse/DIA-5445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DIA-5445] Fix vendor details view on tvOS

ConsentViewController/Classes/Consents/SPPreferencesConsent.swift, ConsentViewController/Classes/SourcePointClient/Adapters.swift, Example/ObjC-ExampleApp/ViewController.m, Example/ObjC-ExampleAppUITests/ExampleApp.swift, Example/ObjC-ExampleAppUITests/ObjC_ExampleAppUITests.swift
* make fields inside `SPPreferencesConsent` (and its subclasses) `public`
* make `SPPreferencesConsent` subclasses `objc` compatible
=> make fields on `SPPreferencesConsent` public and objc compatible
