ConsentViewController/Classes/ConsentViewController.swift, ConsentViewController/Classes/SourcePointClient.swift, Example/ConsentViewController.xcodeproj/project.pbxproj, Example/ConsentViewController.xcodeproj/xcshareddata/xcschemes/ConsentViewController-Example.xcscheme, Example/ConsentViewController/Base.lproj/Main.storyboard, Example/ConsentViewController/Info.plist, Example/ConsentViewController/ViewController.swift, Example/Podfile.lock, Example/Pods/Local Podspecs/ConsentViewController.podspec.json, Example/Pods/Manifest.lock, Example/Pods/Pods.xcodeproj/project.pbxproj, Example/Pods/Target Support Files/ConsentViewController/ConsentViewController-Info.plist, Example/Pods/Target Support Files/ConsentViewController/ResourceBundle-ConsentViewController-ConsentViewController-Info.plist
@vilasma for some reason the changes were not in the development branch either. This PR brings the changes from the latest release back to the master branch and simplifies the Example/ViewController
=> Update consent view controller

ConsentViewController/Classes/ConsentViewControllerError.swift
Instead so showing failure reason, error description and help message to user now we are showing only error description to user.
=> Changed error description as suggested by QA

ConsentViewController/Classes/ConsentViewController.swift, Example/ConsentViewController/ViewController.swift
Error handling for getSiteId and getCustomConsent API is added.
=> Handled error thrown by GetSiteID API call in SDK

ConsentViewController/Classes/ConsentViewController.swift
Now we are making the GDPR status check continue with every n/w call and we are storing the GDPR data and instead of waiting for the result we are proceeding with other n/w calls  as we don't have any dependency on the GDPR n/w call for main n/w calls.
=> Removed the dependency of GDPR Status API call to proceed with other n/w calls.

CHANGELOG.md, ConsentViewController/Assets/JSReceiver.js, ConsentViewController/Classes/ConsentDelegate.swift, ConsentViewController/Classes/ConsentViewController.swift, ConsentViewController/Classes/Logger.swift, ConsentViewController/Classes/SourcePointClient.swift, Example/ConsentViewController.xcodeproj/project.pbxproj, Example/ConsentViewController/Info.plist, Example/ConsentViewController/ViewController.swift, Example/Pods/Pods.xcodeproj/project.pbxproj
changed some query params, some callback events and SDK initialization process...
=> Integrated the new script into SDK

Example/Pods/Pods.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, Example/Pods/Pods.xcodeproj/xcshareddata/xcschemes/ConsentViewController.xcscheme, README.md
Implemented changes for carthage into schem and created a tag 3.0.1 for carthage
=> Carthage Support

ConsentViewController/Classes/ConsentStringSDK/ConsentString.swift
The IAB spec indicates the consent string should be an base64URL but the ConsentString Swift SDK provided by the IAB uses base64. 
Using base64 instead of base64URL breaks some ~very strict~ IAB vendors/frameworks. In this PR we move from b64 to b64URL to fix make sure we follow the TCF framework as it was described.
=> keep base64URL string representation of the consent string instead of base64

ConsentViewController/Classes/GDPRConsentViewController.swift, ConsentViewController/Classes/GDPRPropertyName.swift
=> update doc comments fro GDPRConsentViewController and GDPRPropertyName

Example/ConsentViewController/ViewController.swift, Example/NativeMessageExample/ViewController.swift
The demo properties have changed. This PR update them to avoid confusion when first cloning the repo.
=> Update Demo Properties

.github/workflows/swift.yml, Example/.swiftlint.yml
In this PR we setup GitHub workflow to lint our code using [SwiftLint](https://realm.github.io/SwiftLint/)
Partially addresses #101 
PS. there are quite a few linting issues that should be fixed in a separate PR
=> Add SwiftLint to GitHub workflow

ConsentViewController/Classes/GDPRConsentViewController.swift
Fixes https://sourcepoint.atlassian.net/browse/SP-3253
=> Store IAB on get message as well

ConsentViewController/Classes/MessageWebViewController.swift
=> [TCFv2] disable zoom on WebMessageViewController

.github/workflows/swift.yml, ConsentViewController/Assets/GDPRJSReceiver.js, ConsentViewController/Classes/GDPRAction.swift, ConsentViewController/Classes/GDPRConsentDelegate.swift, ConsentViewController/Classes/GDPRConsentViewController.swift, ConsentViewController/Classes/GDPRNativeMessageViewController.swift, ConsentViewController/Classes/GDPRUserConsent.swift, ConsentViewController/Classes/MessageWebViewController.swift, ConsentViewController/Classes/SPGDPRArbitraryJson.swift, ConsentViewController/Classes/SourcePointClient.swift, ConsentViewController/Classes/SourcePointRequestsResponses.swift, Example/ConsentViewController.xcodeproj/project.pbxproj, Example/ConsentViewController_ExampleTests/ConsentViewController_ExampleTests.swift, Example/ConsentViewController_ExampleTests/SPGDPRArbitraryJsonSpec.swift, Example/NativeMessageExample/ViewController.swift, Example/Pods/Pods.xcodeproj/project.pbxproj
We now get the payload passed by the PM when hitting _Save & Exit_ action and pass that to the Wrapper API.
=> Add PM's payload to save and exit

ConsentViewController/Assets/GDPRJSReceiver.js, ConsentViewController/Classes/GDPRConsentDelegate.swift, ConsentViewController/Classes/GDPRConsentViewController.swift, ConsentViewController/Classes/MessageWebViewController.swift, Example/ConsentViewController/ViewController.swift
* renamed `pmWillShow/DidDisappear` to `gdprPMWillShow/DidDisappear`
* fixed `gdprPMWillShow/DidDisappear` not firing
=> Fix consent delegate methods v4

ConsentViewController/Assets/GDPRJSReceiver.js, ConsentViewController/Classes/MessageWebViewController.swift, Example/ConsentViewController_ExampleTests/MessageWebViewControllerSpec.swift
* Fix methods `messageDidDisappear` and `gdprPmDidDisappear` that weren't firing. 
* Refactored JSReceiver
=> fix `*didDisappear` ConsentDelegate methods

ConsentViewController/Classes/GDPRConsentViewController.swift, Example/ConsentViewController_ExampleTests/GDPRConsentViewControllerSpec.swift
In order to avoid keeping stale IAB data in the `UserDefaults` we're now flushing all IAB related data before writing the new one to it. 
⚠️ we should wait for #134 to be merged, then rebase this one on top of develop
=> [SP-3371] Flush TCF data on consent

.github/workflows/swift.yml, ConsentViewController/Classes/ConnectivityManager.swift, ConsentViewController/Classes/GDPRConsentViewController.swift, ConsentViewController/Classes/MessageWebViewController.swift, ConsentViewController/Classes/SourcePointClient.swift, Example/ConsentViewController_ExampleTests/ConnectivityManagerSpec.swift, Example/ConsentViewController_ExampleTests/SourcePointClientSpec.swift
Removed strong reference of OnError, onwards passing error in completion handler also removed shared instance of Connectivity Manager. updated unit test cases for the same.
=> Removed strong reference of OnError

ConsentViewController/Classes/MessageWebViewController.swift
=> Disable vertical bounce of webview

ConsentViewController/Classes/GDPRConsentViewController.swift, ConsentViewController/Classes/GDPRUserConsent.swift, ConsentViewController/Classes/SourcePointRequestsResponses.swift, Example/ConsentViewController_ExampleTests/GDPRConsentViewControllerSpec.swift, Example/ConsentViewController_ExampleTests/Helpers/SourcePointClientMock.swift, Example/ConsentViewController_ExampleTests/MessageWebViewControllerSpec.swift, Example/ConsentViewController_ExampleTests/SourcePointClient/SourcePointClientSpec.swift
=> [SP-4056] add vendorGrants to customConsent completionHandler

ConsentViewController/Classes/MessageWebViewController.swift
Disabled allowsBackForwardNavigationGestures on SDK WebView
=> [SP-4433] Disable BackForward navigation gestures for webview

Example/ConsentViewController.xcodeproj/project.pbxproj, Example/SourcePointMetaAppUITests/Helpers/MetaApp.swift, Example/SourcePointMetaAppUITests/Helpers/PropertyData.swift, Example/SourcePointMetaAppUITests/MetaAppValidationUITests.swift
Added native UI tests for MetaApp validation
=> [SP-4437] Native UI tests for MetaApp validation

ConsentViewController/Classes/MessageWebViewController.swift
=> expand MessageWebView error handler

ConsentViewController/Classes/GDPRConsentDelegate.swift, ConsentViewController/Classes/GDPRConsentViewController.swift, ConsentViewController/Classes/MessageWebViewController.swift, ConsentViewController/Classes/OSLogger.swift, ConsentViewController/Classes/SPDeviceManager.swift, ConsentViewController/Classes/SourcePointClient/ErrorMetricsRequest.swift, ConsentViewController/Classes/SourcePointClient/SimpleClient.swift, ConsentViewController/Classes/SourcePointClient/SourcePointClient.swift, Example/ConsentViewController.xcodeproj/project.pbxproj, Example/ConsentViewController/ViewController.swift, Example/ConsentViewController_ExampleTests/GDPRConsentViewControllerSpec.swift, Example/ConsentViewController_ExampleTests/Helpers/HttpMock.swift, Example/ConsentViewController_ExampleTests/Helpers/MockConsentDelegate.swift, Example/ConsentViewController_ExampleTests/Helpers/SourcePointClientMock.swift, Example/ConsentViewController_ExampleTests/SPDeviceSpec.swift, Example/ConsentViewController_ExampleTests/SourcePointClient/SourcePointClientSpec.swift, Example/Pods/Pods.xcodeproj/project.pbxproj, SPLegislation.swift
* refactor `GDPRConsentDelegate.onError` to receive non-optional Error parameter
* make sure to call the `GDPRConsentViewController.onError` on every error case
* send error metrics to wrapper api
=> SP-5415 send error metrics

ConsentViewController/Classes/GDPRConsentViewController.swift, ConsentViewController/Classes/MessageWebViewController.swift, ConsentViewController/Classes/PrivacyManagerTab.swift, ConsentViewController/Classes/SPLegislation.swift, Example/ConsentViewController.xcodeproj/project.pbxproj, Example/ConsentViewController_ExampleTests/MessageWebViewControllerSpec.swift, Example/ConsentViewController_ExampleTests/PrivacyManagerTabSpec.swift, Example/NativeMessageExample/ViewController.swift, Example/NativeMessageExampleUITests/Helpers/NativeExampleApp.swift, Example/NativeMessageExampleUITests/NativeMessageExampleUITests.swift, Example/Pods/Pods.xcodeproj/project.pbxproj, Example/SourcePointMetaApp/Controllers/AddPropertyViewController/AddPropertyViewController.swift, Example/SourcePointMetaApp/Controllers/GDPRConsentViewController/ConsentDetailsViewController.swift, Example/SourcePointMetaApp/Layers/CoreDataModels/PropertyDetailsModel/PropertyDetails+CoreDataClass.swift, Example/SourcePointMetaApp/Layers/CoreDataModels/PropertyDetailsModel/PropertyDetails+CoreDataProperties.swift, Example/SourcePointMetaApp/Layers/DatabaseCoordinator/PropertyDetailsCoordinator/PropertyDetailsStorageCoordinator.swift, Example/SourcePointMetaApp/Layers/Models/PropertyDetailsModel/PropertyDetailsModel.swift, Example/SourcePointMetaApp/Layers/ViewModels/AddPropertyViewModel/AddPropertyViewModel.swift, Example/SourcePointMetaApp/Layers/ViewModels/PropertyListViewModel/PropertyListViewModel.swift, Example/SourcePointMetaApp/SourcePointMetaApp.xcdatamodeld/.xccurrentversion, Example/SourcePointMetaApp/SourcePointMetaApp.xcdatamodeld/SourcePointMetaApp 4.xcdatamodel/contents, Example/SourcePointMetaApp/Storyboards/Base.lproj/Main.storyboard, Example/SourcePointMetaAppTests/PropertyDetailsStorageCoordinatorTest.swift, Example/SourcePointMetaAppUITests/Helpers/MetaApp.swift, Example/SourcePointMetaAppUITests/NativeMessageUITests.swift
- With this feature user can request pm tab from SDK.
- To have the requested pmTab we need to set the `.privacyManagerTab` attribute of the GDPRConsentViewController before calling `.loadMessage() / .loadPrivacyManager()`.
`consentViewController.privacyManagerTab = .Vendors`                                    
`consentViewController.loadMessage()`
- Added pmTab feature in Meta App
=> [SP-5909] Implemented PMTab feature

ConsentViewController/Classes/SPConsentManager.swift, ConsentViewController/Classes/SourcePointClient/MockNativePMResponse.swift, ConsentViewController/Classes/SourcePointClient/SPNativeUI.swift, ConsentViewController/Classes/SourcePointClient/SPPrivacyManager.swift, ConsentViewController/Classes/SourcePointClient/SourcePointClient.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/SPCategoryDetailsViewController.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/SPManagePreferenceViewController.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/SPNativePrivacyManagerViewController.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/SPNativeScreenViewController.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/SPPMHeader.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/SPPartnersViewController.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/SPPrivacyPolicyViewController.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/SPVendorDetailsViewController.swift, Example/Pods/Pods.xcodeproj/project.pbxproj
Change components to address https://github.com/SourcePointUSA/apple_tv_json/pull/2
=> update MockNativePM and SPNativeUI classes

ConsentViewController/Classes/Consents/SPCCPAConsent.swift, ConsentViewController/Classes/Consents/SPGDPRConsent.swift, ConsentViewController/Classes/SPConsentManager.swift, ConsentViewController/Classes/SPIDFAStatus.swift, ConsentViewController/Classes/SourcePointClient/ConsentRequestResponse.swift, ConsentViewController/Classes/SourcePointClient/MessageResponse.swift, ConsentViewController/Classes/SourcePointClient/SPNativeUI.swift, ConsentViewController/Classes/SourcePointClient/SourcePointClient.swift
* add `uuid` to `SPGDPRConsent` 
* add `uuid` to `SPCCPAConsent`
=> SP-7373 bring consent UUIDs back

ConsentViewController/Classes/SPConsentManager.swift
We have encountered a crash due to a force unrwap under tvOS. Error is TBD
=> Avoid force unwrap for nativePMMessage

ConsentViewController/Assets/javascript/SPJSReceiver.js, ConsentViewController/Classes/Consents/SPGDPRConsent.swift, ConsentViewController/Classes/Consents/SPUserData.swift, ConsentViewController/Classes/SPAction.swift, ConsentViewController/Classes/SPConsentManager.swift, ConsentViewController/Classes/SPSDK.swift, ConsentViewController/Classes/SourcePointClient/SourcePointClient.swift, ConsentViewController/Classes/Views/iOS/SPWebMessageViewController.swift, Example/ConsentViewController_ExampleTests/Helpers/GDPRUIiDelegateMock.swift, Example/ConsentViewController_ExampleTests/Helpers/SourcePointClientMock.swift, Example/ConsentViewController_ExampleTests/SPNativeMessageViewControllerSpec.swift, README.md
* add a new action type `Custom`.
=> SP-7839 implement custom action

README.md
Added information for the 5 event callbacks
=> Add event callback section

ConsentViewController/Classes/SPError.swift, ConsentViewController/Classes/SourcePointClient/SourcePointClient.swift, Example/ConsentViewController_ExampleTests/SPErrorSpec.swift
Range of SPErrors added with message to specify the endpoint which is in trouble
=> SP-8574 fix misleading error message

ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/CCPA/SPCCPAManagePreferenceViewController.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/CCPA/SPCCPAManagePreferenceViewController.xib, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/CCPA/SPCCPANativePrivacyManagerViewController.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/CCPA/SPCCPANativePrivacyManagerViewController.xib, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/Common/SPNativeScreenViewController.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/GDPR/SPGDPRManagePreferenceViewController.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/GDPR/SPGDPRManagePreferenceViewController.xib, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/GDPR/SPGDPRNativePrivacyManagerViewController.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/GDPR/SPGDPRNativePrivacyManagerViewController.xib
Purpose description label removed from first CCPA & GDPR views
=> SP-8966 remove purpose description

ConsentViewController/Classes/Consents/ConsentStatus.swift, ConsentViewController/Classes/Constants.swift, ConsentViewController/Classes/Extensions/SPURLExtensions.swift, ConsentViewController/Classes/SPError.swift, ConsentViewController/Classes/SourcePointClient/ConsentStatusMetadata.swift, ConsentViewController/Classes/SourcePointClient/ConsentStatusResponse.swift, ConsentViewController/Classes/SourcePointClient/QueryParamEncodableProtocol.swift, ConsentViewController/Classes/SourcePointClient/SourcePointClient.swift, Example/ConsentViewController.xcodeproj/project.pbxproj, Example/ConsentViewController_ExampleTests/Helpers/HttpMock.swift, Example/ConsentViewController_ExampleTests/Helpers/SourcePointClientMock.swift, Example/ConsentViewController_ExampleTests/SPDateCreatedSpec.swift, Example/ConsentViewController_ExampleTests/SourcePointClient/QueryParamEncodableSpec.swift, Example/ConsentViewController_ExampleTests/SourcePointClient/SourcePointClientSpec.swift, Example/ConsentViewController_ExampleTests/SourcePointClient/UnmockedSourcepointClientSpec.swift, Example/Pods/Pods.xcodeproj/project.pbxproj, SPDateCreated.swift
https://sourcepoint.atlassian.net/browse/DIA-1179
=> DIA-1179 call to consent status

ConsentViewController/Classes/Constants.swift, ConsentViewController/Classes/SourcePointClient/SourcePointClient.swift, Example/ConsentViewController_ExampleTests/Helpers/SourcePointClientMock.swift, Example/ConsentViewController_ExampleTests/SourcePointClient/UnmockedSourcepointClientSpec.swift
=> [DIA-1247] `/meta-data` fix

ConsentViewController/Assets/javascript/SPJSReceiver.js, ConsentViewController/Classes/SPIDFAStatus.swift, Example/ConsentViewController.xcodeproj/project.pbxproj, Example/ConsentViewController.xcodeproj/xcshareddata/xcschemes/NativeMessageExample.xcscheme, Example/ConsentViewController.xcodeproj/xcshareddata/xcschemes/ObjC-ExampleApp.xcscheme, Example/ConsentViewController/ViewController.swift, Example/NativeMessageExample/Base.lproj/Main.storyboard, Example/NativeMessageExample/ViewController.swift, Example/NativeMessageExampleUITests/Helpers/CustomMatchers.swift, Example/NativeMessageExampleUITests/Helpers/NativeExampleApp.swift, Example/NativeMessageExampleUITests/NativeMessageExampleUITests.swift, Example/ObjC-ExampleApp/Base.lproj/Main.storyboard, Example/ObjC-ExampleApp/SPSdkStatus.h, Example/ObjC-ExampleApp/ViewController.m, Example/ObjC-ExampleAppUITests/CustomMatchers.swift, Example/ObjC-ExampleAppUITests/ExampleApp.swift, Example/ObjC-ExampleAppUITests/ObjC_ExampleAppUITests.swift
Add `customActionId` to PM's action payload to fully support custom action coming from PM
https://sourcepoint.atlassian.net/browse/DIA-1390
=> DIA-1390 add customActionId to pm action payload

ConsentViewController/Classes/Consents/SPCCPAConsent.swift, ConsentViewController/Classes/Consents/SPUserData.swift, Example/ConsentViewController.xcodeproj/project.pbxproj, Example/ConsentViewController.xcworkspace/xcshareddata/swiftpm/Package.resolved, Example/ConsentViewController_ExampleTests/CCPAConsentStatusSpec.swift, Example/ConsentViewController_ExampleTests/CustomMatchers.swift, Example/ConsentViewController_ExampleTests/SPConsentSpec.swift
This should prevent the SDK from throwing error when new values are added to CCPA consent status
=> [DIA-1694]v6 / add .Unknown and .LinkedNoAction to CCPAConsentStatus

ConsentViewController/Classes/SourcePointClient/MessagesRequest.swift, ConsentViewController/Classes/SourcePointClient/SourcepointClientCoordinator.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SourcePointClient/SourcePointClientSpec.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SourcePointClient/UnmockedSourcepointClientSpec.swift
… not the part of the body anymore
=> [DIA-1915] localState is sent as query parameter,

ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/GDPR/SPGDPRNativePrivacyManagerViewController.swift
This branch contains the fix for v7
=> [DIA-1840] construction of a header cell is removed from the HomeView's table view for tvOS

ConsentViewController/Classes/SourcePointClient/MessagesRequest.swift, ConsentViewController/Classes/SourcePointClient/SourcepointClientCoordinator.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SourcePointClient/SourcePointClientSpec.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SourcePointClient/UnmockedSourcepointClientSpec.swift
This PR reviews the request to `/messages`.
=> DIA-2459 move localState to body param of messages request

ConsentViewController/Classes/SPError.swift, ConsentViewController/Classes/SourcePointClient/SimpleClient.swift, ConsentViewController/Classes/SourcePointClient/SourcePointClient.swift, ConsentViewController/Classes/Views/iOS/SPWebMessageViewController.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/Common/SPNativeScreenViewController.swift, Example/ConsentViewController_ExampleTests/Helpers/CustomMatchers.swift, Example/ConsentViewController_ExampleTests/Helpers/HttpMock.swift, Example/ConsentViewController_ExampleTests/Helpers/SourcePointClientMock.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SourcePointClient/SimpleClientSpec.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SourcePointClient/SourcePointClientSpec.swift, Example/ConsentViewController_ExampleTests/SPErrorSpec.swift, Example/NativePMExampleAppUITests/CustomMatchers.swift, Example/SPGDPRExampleAppUITests/Helpers/CustomMatchers.swift
* Refactor `SourcePointClient` to pass errors from `SimpleClient` along
* Remove unused error classes
* Fix test build for XCode 15
=> Add status code to errors and refactor SPClient

ConsentViewController/Classes/SPDateCreated.swift
=> add formatter locale to SPDateCreated

ConsentViewController/Classes/SPConsentManager.swift, ConsentViewController/Classes/Views/iOS/SPWebMessageViewController.swift
Fix of the bug https://sourcepoint.atlassian.net/browse/DIA-2816
Reconsent triggered on vendor add/Legal bases change in VL is causing all previously given consents to reset
=> [DIA-2816] `uuid` is added to `pmurl` 

ConsentViewController/Classes/Consents/ConsentStatus.swift, ConsentViewController/Classes/Consents/SPGDPRConsent.swift
https://sourcepoint.atlassian.net/browse/DIA-2838
=> [DIA-2838] Make `consentStatus` `public`

ConsentViewController/Classes/Consents/SPCCPAConsent.swift, ConsentViewController/Classes/Consents/SPGDPRConsent.swift, ConsentViewController/Classes/SPDate.swift, ConsentViewController/Classes/SourcePointClient/ChoiceAllResponse.swift, ConsentViewController/Classes/SourcePointClient/ChoiceResponses.swift, ConsentViewController/Classes/SourcePointClient/ConsentStatusMetadata.swift, ConsentViewController/Classes/SourcePointClient/ConsentStatusResponse.swift, ConsentViewController/Classes/SourcePointClient/MessagesResponse.swift, ConsentViewController/Classes/SourcePointClient/MetaDataRequestResponse.swift, ConsentViewController/Classes/SourcePointClient/SourcepointClientCoordinator.swift, Example/ConsentViewController_ExampleTests/CCPAConsentStatusSpec.swift, Example/ConsentViewController_ExampleTests/Helpers/SourcePointClientMock.swift, Example/ConsentViewController_ExampleTests/SPConsentManagerSpec.swift, Example/ConsentViewController_ExampleTests/SPDateCreatedSpec.swift, Example/ConsentViewController_ExampleTests/SPGDPRConsentsSpec.swift, Example/Pods/Pods.xcodeproj/project.pbxproj
So we can reuse the class for dates other than `createdDate`.
=> rename `SPDateCreated` to `SPDate`

ConsentViewController/Classes/Consents/SPCCPAConsent.swift, ConsentViewController/Classes/SourcePointClient/ChoiceAllResponse.swift, ConsentViewController/Classes/SourcePointClient/ConsentStatusResponse.swift, ConsentViewController/Classes/SourcePointClient/SourcepointClientCoordinator.swift, Example/ConsentViewController_ExampleTests/CCPAConsentStatusSpec.swift, Example/ConsentViewController_ExampleTests/SPCCPAConsentSpec.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SPClientCoordinatorSpec.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SourcePointClient/CampaignSpec.swift, Example/ConsentViewController_ExampleTests/SPConsentManagerSpec.swift, Example/ConsentViewController_ExampleTests/SPConsentSpec.swift
* add `expirationDate` to `SPCCPAConsent` and response classes
* reset CCPA consent to `.empty()` if ccpa consent `.expirationDate < today`
=> DIA-2895 CCPA consent expiration

ConsentViewController/Classes/Consents/ConsentStatus.swift, ConsentViewController/Classes/Consents/SPUSNatConsent.swift, ConsentViewController/Classes/SourcePointClient/PvDataRequestResponse.swift, ConsentViewController/Classes/SourcePointClient/SourcepointClientCoordinator.swift, Example/ConsentViewController_ExampleTests/Helpers/SourcePointClientMock.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SPClientCoordinatorSpec.swift, Example/ConsentViewController_ExampleTests/SPConsentSpec.swift, Example/ConsentViewController_ExampleTests/SPUSNatConsentSpec.swift
* add `consentStatus` object to `SPUSNatConsent`
* add `usnat` to `/pv-data` request and response
* handle with `usnat` campaign on `/pv-data` response
=> DIA-2623 add usnat to `pv-data`

ConsentViewController/Classes/Consents/ConsentStatus.swift, ConsentViewController/Classes/Consents/SPUSNatConsent.swift, ConsentViewController/Classes/SourcePointClient/ChoiceResponses.swift, ConsentViewController/Classes/SourcePointClient/ConsentStatusResponse.swift, ConsentViewController/Classes/SourcePointClient/MessagesResponse.swift, ConsentViewController/Classes/SourcePointClient/SourcepointClientCoordinator.swift, Example/ConsentViewController_ExampleTests/Helpers/SourcePointClientMock.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SPClientCoordinatorSpec.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SourcePointClient/CampaignSpec.swift, Example/ConsentViewController_ExampleTests/SPConsentSpec.swift, Example/ConsentViewController_ExampleTests/SPUSNatConsentSpec.swift
* Add `expirationDate` to `SPUSNatConsent`
* Handle consent expiration on SPCoordinator
=> DIA-3007 handle consent expiration for usnat

ConsentViewController/Classes/Consents/SPUSNatConsent.swift, ConsentViewController/Classes/SPConsentManager.swift, ConsentViewController/Classes/SourcePointClient/ChoiceResponses.swift, ConsentViewController/Classes/SourcePointClient/ConsentStatusResponse.swift, ConsentViewController/Classes/SourcePointClient/MessagesResponse.swift, ConsentViewController/Classes/SourcePointClient/SourcepointClientCoordinator.swift, Example/ConsentViewController_ExampleTests/Helpers/SourcePointClientMock.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SPClientCoordinatorSpec.swift, Example/ConsentViewController_ExampleTests/SPConsentManagerSpec.swift, Example/ConsentViewController_ExampleTests/SPConsentSpec.swift, Example/ConsentViewController_ExampleTests/SPUSNatConsentSpec.swift
* Add GPPData to usnat consent class
* Store GPPData in the local storage
=> DIA-3211 store usnat GPPData

ConsentViewController.podspec, ConsentViewController/Classes/SourcePointClient/Adapters.swift, ConsentViewController/Classes/SourcePointClient/SPPublisherData.swift, ConsentViewController/Classes/SourcePointClient/SourcePointClient.swift, ConsentViewController/Classes/SourcePointClient/SourcepointClientCoordinator.swift, Example/ConsentViewController.xcworkspace/xcshareddata/swiftpm/Package.resolved, Example/ConsentViewController_ExampleTests/Helpers/SourcePointClientMock.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SPClientCoordinatorSpec.swift, Example/ConsentViewController_ExampleTests/SPClientCoordinator/SourcePointClient/UnmockedSourcepointClientSpec.swift, Example/Podfile.lock, Example/Pods/Local Podspecs/ConsentViewController.podspec.json, Example/Pods/Manifest.lock, Example/Pods/SPMobileCore/SPMobileCore.xcframework/Info.plist, Example/Pods/SPMobileCore/SPMobileCore.xcframework/ios-arm64/SPMobileCore.framework/Headers/SPMobileCore.h, Example/Pods/SPMobileCore/SPMobileCore.xcframework/ios-arm64/SPMobileCore.framework/Modules/module.modulemap, Example/Pods/SPMobileCore/SPMobileCore.xcframework/ios-arm64_x86_64-simulator/SPMobileCore.framework/Headers/SPMobileCore.h, Example/Pods/SPMobileCore/SPMobileCore.xcframework/ios-arm64_x86_64-simulator/SPMobileCore.framework/Modules/module.modulemap, Example/Pods/SPMobileCore/SPMobileCore.xcframework/tvos-arm64/SPMobileCore.framework/Headers/SPMobileCore.h, Example/Pods/SPMobileCore/SPMobileCore.xcframework/tvos-arm64/SPMobileCore.framework/Modules/module.modulemap, Example/Pods/SPMobileCore/SPMobileCore.xcframework/tvos-arm64_x86_64-simulator/SPMobileCore.framework/Headers/SPMobileCore.h, Example/Pods/SPMobileCore/SPMobileCore.xcframework/tvos-arm64_x86_64-simulator/SPMobileCore.framework/Modules/module.modulemap
[DIA-3500](https://sourcepoint.atlassian.net/browse/DIA-3500) Implement POST pv-data call
[DIA-3500]: https://sourcepoint.atlassian.net/browse/DIA-3500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DIA-3500 Integrate `postPvData`

ConsentViewController/Classes/SourcePointClient/Adapters.swift, ConsentViewController/Classes/SourcePointClient/SourcePointClient.swift
[DIA-4801](https://sourcepoint.atlassian.net/browse/DIA-4801)  [iOS] implement and integrate POST ReportIdfaStatus
[DIA-4801]: https://sourcepoint.atlassian.net/browse/DIA-4801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DIA-4801] Add core `reportIdfaStatus` post method

ConsentViewController/Classes/SourcePointClient/SourcepointClientCoordinator.swift, Example/ConsentViewController_ExampleTests/SPErrorSpec.swift
Change due to https://github.com/SourcePointUSA/mobile-core/pull/32/сommits/4242daf9594b0a9217e17a75ccf68eccc8526c29
=> Change due to `fun setTranslateMessage()` addition to `ICoordinator`

ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/CCPA/SPCCPAManagePreferenceViewController.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/Common/SPNativeScreenViewController.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/GDPR/SPGDPRManagePreferenceViewController.swift
[DIA-5435](https://sourcepoint.atlassian.net/browse/DIA-5435) Missing text component in category view
[DIA-5435]: https://sourcepoint.atlassian.net/browse/DIA-5435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DIA-5435] add missing text category view

.github/workflows/CreateJiraTicket.yml
https://sourcepoint.atlassian.net/browse/DEVOPS2-1846
=> [DEVOPS2-1846] github actions should minimize 3rd party actions and pin to specific shas

ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/CCPA/SPCCPACategoryDetailsViewController.xib, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/CCPA/SPCCPAManagePreferenceViewController.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/CCPA/SPCCPAManagePreferenceViewController.xib, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/Common/LongButtonViewCell.xib, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/Common/SPNativeScreenViewController.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/GDPR/SPGDPRCategoryDetailsViewController.xib, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/GDPR/SPGDPRManagePreferenceViewController.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/GDPR/SPGDPRManagePreferenceViewController.xib
[DIA-5441](https://sourcepoint.atlassian.net/browse/DIA-5441) Descriptions and Stack/ purpose names are truncated and illegible
[DIA-5441]: https://sourcepoint.atlassian.net/browse/DIA-5441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DIA-5441] Make texts not truncated across the tvOS

ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/CCPA/SPCCPACategoryDetailsViewController.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/CCPA/SPCCPANativePrivacyManagerViewController.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/CCPA/SPCCPAVendorDetailsViewController.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/Common/LongButtonViewCell.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/Common/SPNativeScreenViewController.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/GDPR/SPGDPRCategoryDetailsViewController.swift, ConsentViewController/Classes/Views/tvOS/NativePrivacyManager/GDPR/SPGDPRNativePrivacyManagerViewController.swift
[DIA-5443](https://sourcepoint.atlassian.net/browse/DIA-5443) Auto sizing causes random wildly inconsistent font sizes
[DIA-5443]: https://sourcepoint.atlassian.net/browse/DIA-5443?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DIA-5443] Fix inconsistent font sizes

ConsentViewController.podspec, ConsentViewController/Classes/Consents/SPPreferencesConsent.swift, ConsentViewController/Classes/SourcePointClient/Adapters/SPUserDataCoreToNativeAdapter.swift, Example/Podfile.lock, Example/Pods/Local Podspecs/ConsentViewController.podspec.json, Example/Pods/Manifest.lock, Example/Pods/SPMobileCore/SPMobileCore.xcframework/Info.plist, Example/Pods/SPMobileCore/SPMobileCore.xcframework/ios-arm64/SPMobileCore.framework/Headers/SPMobileCore.h, Example/Pods/SPMobileCore/SPMobileCore.xcframework/ios-arm64_x86_64-simulator/SPMobileCore.framework/Headers/SPMobileCore.h, Example/Pods/SPMobileCore/SPMobileCore.xcframework/tvos-arm64/SPMobileCore.framework/Headers/SPMobileCore.h, Example/Pods/SPMobileCore/SPMobileCore.xcframework/tvos-arm64_x86_64-simulator/SPMobileCore.framework/Headers/SPMobileCore.h
Waiting on https://github.com/SourcePointUSA/mobile-core/pull/76 to be merged.
=> DIA-5922 add `versionId` preferences consents
